spring.application.name=eventflow

spring.datasource.url=jdbc:postgresql://localhost:5432/eventflow
spring.datasource.username=eventflow_user
spring.datasource.password=eventflow_pass

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true